### ISSUE TITLE
Pre-compiling the middleware stack

### ISSUE THREAD

**Issue by mholt** [carbocation/interpose#8]
The ServeHTTP method has this code:

```go
//Initialize with an empty http.Handler
next := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {}))
//Call the middleware stack in FIFO order
for i := len(mw.Wares) - 1; i >= 0; i-- {
	next = mw.Wares[i](next)
}
//Finally, serve back up the chain
next.ServeHTTP(w, req)
```

I haven't done benchmarks, but do you think the chain could be compiled when the server starts listening, rather than on every HTTP request? And I bet we could get rid of that empty handler too.

I've been working on a package modeled a little bit after interpose because it's an elegant way to stack middleware. I was able to tweak the process and get it down to this (mine stacks HandlerFuncs, not Handlers, but same idea):

```go
mw.stack = server.ServeHTTP // or whatever the main handler is (the "C" in A-B-C-B-A middlewares)
for _, middleware := range mw.Wares {
	mw.stack = middleware(mw.stack)
}
```

That's just an example. Of course you could change the order and stuff. And obviously it requires knowing what the core or inner-most HTTP handler is, and then a call to some compilation function. But then the ServeHTTP method could be as simple as:

```go
func (mw *Middleware) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	mw.stack(w, req)
}
```

Not sure if that made any sense. But it's just a suggestion. This pattern might be able to eliminate that no-op handler and speed up request handling (though probably just a little bit).

**Comment by carbocation** [comment]
Very interesting. Let me see if I can get some benchmarks - if it's faster, would definitely incorporate this.

**Comment by carbocation** [comment]
Please take a look at 35a997f84ecef50688e6ba5fe2b9a7651289f907 (branch "compiled") and let me know your thoughts. I have not yet tried this on a large project to guarantee that it actually works. It does seem to take about 20% less time per request with the basic benchmark I set up ( try `go test -bench="."`)

**Comment by mholt** [comment]
I've been meaning to take a look at that -- it will stay at the top of my inbox until I do. I'm just trying to get some university assignments done; sorry for holding it up!

**Comment by doug** [comment]
Sorry should have posted here first. Check out my thoughts in #9, having read both I think the approach of making it explicit has a lot of benefit over the "compiled" branch where the user of the library misses out on some control and cannot recompile.

**Comment by carbocation** [comment]
I like @doug 's solution to this better than mine since it preserves backward compatibility and relies on less magic, so I've merged his into master. Cheers!
